// 根據你的課本 Unit 1 ~ Unit 5 字彙掃描站建立的完整單字與片語庫
window.wordDatabase = [
    // --- Unit 1: How Was the Weather in Australia? ---
    { word: "summer vacation", pos: "片", zh: "暑假", en_eg: "I went to Japan during my summer vacation.", zh_eg: "我在暑假去了日本。" },
    { word: "weather", pos: "n.", zh: "天氣", en_eg: "The weather today is very nice.", zh_eg: "今天的天氣非常好。" },
    { word: "Taiwan", pos: "n.", zh: "臺灣", en_eg: "Taiwan is a beautiful island.", zh_eg: "臺灣是一個美麗的島嶼。" },
    { word: "fun", pos: "adj.", zh: "樂趣的；有趣的", en_eg: "Learning English can be a lot of fun.", zh_eg: "學英文可以很有趣。" },
    { word: "snow", pos: "v./n.", zh: "下雪；雪", en_eg: "It often snows in winter here.", zh_eg: "這裡冬天常下雪。" },
    { word: "send", pos: "v.", zh: "寄；送", en_eg: "I want to send a letter to my friend.", zh_eg: "我想寄一封信給我的朋友。" },
    { word: "postcard", pos: "n.", zh: "明信片", en_eg: "She sent me a postcard from Paris.", zh_eg: "她從巴黎寄了一張明信片給我。" },
    { word: "borrow", pos: "v.", zh: "借 (入)", en_eg: "Can I borrow your umbrella?", zh_eg: "我可以借你的雨傘嗎？" },
    { word: "lend", pos: "v.", zh: "借 (出)", en_eg: "He lent me his bike for the day.", zh_eg: "他今天把腳踏車借給我。" },
    { word: "glove", pos: "n.", zh: "手套", en_eg: "Wear your gloves; it's cold outside.", zh_eg: "戴上手套，外面很冷。" },
    { word: "kind", pos: "adj.", zh: "親切的；有同情心的", en_eg: "It is very kind of you to help me.", zh_eg: "你幫忙我真是太親切了。" },
    { word: "lovely", pos: "adj.", zh: "可愛的；美好的", en_eg: "We had a lovely time at the party.", zh_eg: "我們在派對上度過了美好的時光。" },
    { word: "jacket", pos: "n.", zh: "夾克", en_eg: "Put on your jacket before you go out.", zh_eg: "出門前穿上你的夾克。" },
    { word: "give", pos: "v.", zh: "給予", en_eg: "She gave me a piece of advice.", zh_eg: "她給了我一個建議。" },
    { word: "hate", pos: "v.", zh: "討厭", en_eg: "I hate getting up early on cold mornings.", zh_eg: "我討厭在寒冷的早晨早起。" },
    { word: "heavy", pos: "adj.", zh: "厚重的；大量的", en_eg: "We had heavy rain last night.", zh_eg: "昨晚我們遇到了大雨。" },
    { word: "season", pos: "n.", zh: "季節", en_eg: "Spring is my favorite season of the year.", zh_eg: "春天是我一年中最喜歡的季節。" },
    { word: "spring", pos: "n.", zh: "春天", en_eg: "Flowers begin to bloom in spring.", zh_eg: "花朵在春天開始綻放。" },
    { word: "cloud", pos: "n.", zh: "雲", en_eg: "There are dark clouds in the sky.", zh_eg: "天空中有烏雲。" },
    { word: "sun", pos: "n.", zh: "太陽", en_eg: "The sun shines brightly today.", zh_eg: "今天太陽耀眼。" },
    { word: "autumn", pos: "n.", zh: "秋天", en_eg: "Leaves turn red in autumn.", zh_eg: "秋天時樹葉變紅。" },
    { word: "wind", pos: "n.", zh: "風", en_eg: "The strong wind blew my hat off.", zh_eg: "強風把我的帽子吹掉了。" },
    { word: "winter", pos: "n.", zh: "冬天", en_eg: "Birds fly south for the winter.", zh_eg: "鳥類在冬天飛往南方。" },
    { word: "sunny", pos: "adj.", zh: "陽光普照的", en_eg: "It is a sunny day for a picnic.", zh_eg: "今天是野餐的好晴天。" },
    { word: "snowy", pos: "adj.", zh: "有雪的；下雪的", en_eg: "The roads are snowy and slippery.", zh_eg: "道路積雪且滑。" },
    { word: "rainy", pos: "adj.", zh: "有雨的；下雨的", en_eg: "Stay indoors on a rainy day.", zh_eg: "下雨天待在室內。" },
    { word: "cloudy", pos: "adj.", zh: "多雲的", en_eg: "The weather is cloudy and cool.", zh_eg: "天氣多雲且涼爽。" },
    { word: "windy", pos: "adj.", zh: "風大的", en_eg: "It's too windy to fly a kite.", zh_eg: "風太大不能放風箏。" },
    { word: "speak", pos: "v.", zh: "講話", en_eg: "He can speak English very well.", zh_eg: "他英文講得很好。" },
    { word: "mad", pos: "adj.", zh: "生氣的", en_eg: "Don't be mad at me.", zh_eg: "不要生我的氣。" },
    { word: "in fact", pos: "片", zh: "事實上", en_eg: "In fact, I have never been there.", zh_eg: "事實上，我從沒去過那裡。" },
    { word: "mean", pos: "v.", zh: "意指", en_eg: "What does this word mean?", zh_eg: "這個單字是什麼意思？" },
    { word: "another", pos: "adj./pron.", zh: "另一 (個)", en_eg: "Would you like another cup of tea?", zh_eg: "你想再來一杯茶嗎？" },
    { word: "order", pos: "v./n.", zh: "點餐；訂購", en_eg: "Are you ready to order now?", zh_eg: "你們現在準備好點餐了嗎？" },
    { word: "strange", pos: "adj.", zh: "奇怪的", en_eg: "I heard a strange noise last night.", zh_eg: "我昨晚聽到奇怪的聲音。" },
    { word: "soon", pos: "adv.", zh: "很快地", en_eg: "I will see you soon.", zh_eg: "我們很快就會見面。" },
    { word: "Rd.", pos: "n.", zh: "路 (Road 的縮寫)", en_eg: "He lives on Chung Hsiao Rd.", zh_eg: "他住在忠孝路。" },
    { word: "ROC", pos: "n.", zh: "中華民國", en_eg: "National Day of the ROC is in October.", zh_eg: "中華民國國慶日在十月。" },
    { word: "cool", pos: "adj.", zh: "涼爽的", en_eg: "The evening breeze is very cool.", zh_eg: "傍晚的微風很涼爽。" },
    { word: "snowboard", pos: "n.", zh: "滑雪板", en_eg: "He bought a new snowboard for winter.", zh_eg: "他為冬天買了一塊新滑雪板。" },
    { word: "anyway", pos: "adv.", zh: "無論如何", en_eg: "It's raining, but I'll go anyway.", zh_eg: "在下雨，但我無論如何都會去。" },

    // --- Unit 2: You Can Learn About Game Design After You Join the Club ---
    { word: "club", pos: "n.", zh: "社團", en_eg: "Which club did you join this term?", zh_eg: "你這學期參加了哪個社團？" },
    { word: "make up one's mind", pos: "片", zh: "下定決心", en_eg: "Make up your mind quickly.", zh_eg: "快點下定決心。" },
    { word: "interesting", pos: "adj.", zh: "有趣的", en_eg: "This book is very interesting.", zh_eg: "這本書非常有趣。" },
    { word: "science", pos: "n.", zh: "科學", en_eg: "Science is my favorite subject.", zh_eg: "科學是我最喜歡的科目。" },
    { word: "subject", pos: "n.", zh: "學科；主題", en_eg: "We study many subjects at school.", zh_eg: "我們在學校學習許多科目。" },
    { word: "hear", pos: "v.", zh: "聽見", en_eg: "Did you hear that sound?", zh_eg: "你有聽到那個聲音嗎？" },
    { word: "same", pos: "adj.", zh: "相同的", en_eg: "We are in the same class.", zh_eg: "我們在同一個班級。" },
    { word: "call", pos: "v.", zh: "打電話；呼叫", en_eg: "I will call you later tonight.", zh_eg: "我今晚晚點打給你。" },
    { word: "tell", pos: "v.", zh: "告訴", en_eg: "Please tell me the truth.", zh_eg: "請告訴我真相。" },
    { word: "pull one's leg", pos: "片", zh: "開玩笑", en_eg: "Are you pulling my leg?", zh_eg: "你在跟我開玩笑嗎？" },
    { word: "poor", pos: "adj.", zh: "不佳的；貧窮的", en_eg: "He came from a poor family.", zh_eg: "他來自貧窮的家庭。" },
    { word: "end", pos: "v./n.", zh: "結尾；結束", en_eg: "The movie came to an end.", zh_eg: "電影結束了。" },
    { word: "whose", pos: "pron.", zh: "誰的", en_eg: "Whose umbrella is this?", zh_eg: "這是誰的雨傘？" },
    { word: "camera", pos: "n.", zh: "相機", en_eg: "She bought a new digital camera.", zh_eg: "她買了一台新數位相機。" },
    { word: "mine", pos: "pron.", zh: "我的 (東西)", en_eg: "This pen is mine.", zh_eg: "這支筆是我的。" },
    { word: "wrong", pos: "adj.", zh: "錯誤的", en_eg: "I got the wrong answer.", zh_eg: "我得到了錯誤的答案。" },
    { word: "hold on", pos: "片", zh: "稍候", en_eg: "Hold on a minute, please.", zh_eg: "請稍等一下。" },
    { word: "math", pos: "n.", zh: "數學", en_eg: "Math is a challenging subject.", zh_eg: "數學是一個具挑戰性的科目。" },
    { word: "soccer", pos: "n.", zh: "足球", en_eg: "Boys love playing soccer after class.", zh_eg: "男孩們下課後喜歡踢足球。" },
    { word: "Chinese", pos: "adj./n.", zh: "中國的；中文", en_eg: "She is learning Chinese culture.", zh_eg: "她正在學習中國文化。" },
    { word: "history", pos: "n.", zh: "歷史", en_eg: "I like reading world history books.", zh_eg: "我喜歡看世界歷史書。" },
    { word: "violin", pos: "n.", zh: "小提琴", en_eg: "She plays the violin beautifully.", zh_eg: "她小提琴拉得很好聽。" },
    { word: "robot", pos: "n.", zh: "機器人", en_eg: "The robot can walk and talk.", zh_eg: "這機器人會走路也會說話。" },
    { word: "health", pos: "n.", zh: "健康", en_eg: "Health is more important than wealth.", zh_eg: "健康比財富更重要。" },
    { word: "PE", pos: "n.", zh: "體育", en_eg: "We have PE class on Tuesday.", zh_eg: "我們星期二有體育課。" },
    { word: "Ms.", pos: "n.", zh: "女士", en_eg: "Ms. Lee is our English teacher.", zh_eg: "李女士是我們的英文老師。" },
    { word: "engineer", pos: "n.", zh: "工程師", en_eg: "My uncle is a computer engineer.", zh_eg: "我叔叔是一名電腦工程師。" },
    { word: "lesson", pos: "n.", zh: "課；課程", en_eg: "Let's move on to the next lesson.", zh_eg: "我們進入下一課吧。" },
    { word: "difficult", pos: "adj.", zh: "困難的", en_eg: "It is difficult to learn a new language.", zh_eg: "學新語言很困難。" },
    { word: "teach", pos: "v.", zh: "教導", en_eg: "He teaches math at junior high school.", zh_eg: "他在國中教數學。" },
    { word: "own", pos: "adj./v.", zh: "自己的；擁有", en_eg: "I have my own room.", zh_eg: "我有自己的房間。" },
    { word: "finish", pos: "v.", zh: "完成；結束", en_eg: "Have you finished your homework?", zh_eg: "你寫完功課了嗎？" },
    { word: "festival", pos: "n.", zh: "節慶", en_eg: "Dragon Boat Festival is coming.", zh_eg: "端午節快到了。" },
    { word: "start", pos: "v./n.", zh: "開始", en_eg: "Let's start our meeting now.", zh_eg: "我們現在開始開會吧。" },
    { word: "choice", pos: "n.", zh: "選擇", en_eg: "You have no other choice.", zh_eg: "你沒有別的選擇了。" },
    { word: "What's up?", pos: "片", zh: "怎麼了？", en_eg: "Hey, Tom! What's up?", zh_eg: "嘿，湯姆！怎麼了？" },

    // --- Unit 3: Mom Was Doing the Dishes at Half Past Twelve ---
    { word: "someone", pos: "pron.", zh: "某人", en_eg: "Someone is knocking at the door.", zh_eg: "有人在敲門。" },
    { word: "break", pos: "v.", zh: "打破；損壞", en_eg: "Don't break the window.", zh_eg: "不要打破窗戶。" },
    { word: "do the dishes", pos: "片", zh: "洗碗盤", en_eg: "It's my turn to do the dishes tonight.", zh_eg: "今晚輪到我洗碗盤了。" },
    { word: "half", pos: "n.", zh: "一半；二分之一", en_eg: "I spent half of my money.", zh_eg: "我花了我一半的錢。" },
    { word: "past", pos: "prep./adj.", zh: "經過；過去的", en_eg: "It's ten past two.", zh_eg: "現在是兩點十分。" },
    { word: "leave", pos: "v.", zh: "離開", en_eg: "He left home early this morning.", zh_eg: "他今天一大早就離開家了。" },
    { word: "quarter", pos: "n.", zh: "十五分鐘；四分之一", en_eg: "A quarter of an hour is fifteen minutes.", zh_eg: "四分之一小時就是十五分鐘。" },
    { word: "remember", pos: "v.", zh: "記得", en_eg: "Do you remember my name?", zh_eg: "你記得我的名字嗎？" },
    { word: "feed", pos: "v.", zh: "餵養", en_eg: "Feed the cat before you go out.", zh_eg: "出門前先餵貓。" },
    { word: "pet", pos: "n.", zh: "寵物", en_eg: "Do you keep any pets at home?", zh_eg: "你在家裡養寵物嗎？" },
    { word: "sweep", pos: "v.", zh: "掃", en_eg: "Sweep the floor, please.", zh_eg: "請掃地。" },
    { word: "floor", pos: "n.", zh: "地板；樓層", en_eg: "The classroom floor is clean.", zh_eg: "教室的地板很乾淨。" },
    { word: "fix", pos: "v.", zh: "修理；解決", en_eg: "Can you fix my broken watch?", zh_eg: "你能修理我壞掉的手錶嗎？" },
    { word: "drawer", pos: "n.", zh: "抽屜", en_eg: "Put the keys in the desk drawer.", zh_eg: "把鑰匙放在書桌抽屜裡。" },
    { word: "mop", pos: "v./n.", zh: "拖地；拖把", en_eg: "She is mopping the kitchen floor.", zh_eg: "她正在拖廚房地板。" },
    { word: "stairs", pos: "n.", zh: "樓梯", en_eg: "Be careful when walking down the stairs.", zh_eg: "下樓梯時要小心。" },
    { word: "wipe", pos: "v.", zh: "擦拭", en_eg: "Wipe the table with a clean cloth.", zh_eg: "用乾淨的布擦桌子。" },
    { word: "window", pos: "n.", zh: "窗戶", en_eg: "Open the window for some fresh air.", zh_eg: "打開窗戶呼吸新鮮空氣。" },
    { word: "dry", pos: "v./adj.", zh: "(使) 乾燥；乾的", en_eg: "Hang your wet clothes out to dry.", zh_eg: "把濕衣服掛出去晾乾。" },
    { word: "hang", pos: "v.", zh: "吊；掛", en_eg: "Hang your coat on the hook.", zh_eg: "把外套掛在鉤子上。" },
    { word: "clothes", pos: "n.", zh: "衣服", en_eg: "She likes to wear pretty clothes.", zh_eg: "她喜歡穿漂亮的衣服。" },
    { word: "move", pos: "v.", zh: "搬遷；移動", en_eg: "They are moving to Taipei next month.", zh_eg: "他們下個月要搬去台北。" },
    { word: "city", pos: "n.", zh: "城市", en_eg: "Taichung is a big and busy city.", zh_eg: "台中是一個大且繁忙的城市。" },
    { word: "dream", pos: "v./n.", zh: "夢；夢想 (的)", en_eg: "I had a strange dream last night.", zh_eg: "我昨晚做了個奇怪的夢。" },
    { word: "almost", pos: "adv.", zh: "幾乎", en_eg: "I am almost finished with my work.", zh_eg: "我的工作快完成了。" },
    { word: "fall asleep", pos: "片", zh: "睡著", en_eg: "The child fell asleep on the sofa.", zh_eg: "小孩在沙發上睡著了。" },
    { word: "scared", pos: "adj.", zh: "害怕的", en_eg: "Don't be scared of the dark.", zh_eg: "不要害怕黑暗。" },
    { word: "problem", pos: "n.", zh: "問題", en_eg: "Let's solve this math problem together.", zh_eg: "我們一起解開這個數學問題吧。" },
    { word: "tip", pos: "n.", zh: "訣竅", en_eg: "Here are some useful tips for learning English.", zh_eg: "這裡有一些學英文的有益訣竅。" },
    { word: "however", pos: "adv.", zh: "然而", en_eg: "It was raining; however, we still went out.", zh_eg: "雖然在下雨，然而我們還是出門了。" },
    { word: "nothing", pos: "pron.", zh: "沒什麼；無事", en_eg: "There is nothing in the box.", zh_eg: "箱子裡什麼都沒有。" },
    { word: "catch", pos: "v.", zh: "捉；接", en_eg: "He tried to catch the flying ball.", zh_eg: "他試著去接那顆飛球。" },
    { word: "through", pos: "prep.", zh: "穿越；從頭到尾", en_eg: "The train went through a long tunnel.", zh_eg: "火車穿越了一條長隧道。" },
    { word: "finally", pos: "adv.", zh: "終於；最後", en_eg: "He finally passed the difficult exam.", zh_eg: "他終於通過了困難的考試。" },
    { word: "save", pos: "v.", zh: "拯救；存錢", en_eg: "Firefighters saved the cat from the tree.", zh_eg: "消防員把貓從樹上救下來。" },
    { word: "terrible", pos: "adj.", zh: "糟糕的；可怕的", en_eg: "I had a terrible day today.", zh_eg: "我今天過得很糟糕。" },
    { word: "take it easy", pos: "片", zh: "放輕鬆", en_eg: "Take it easy; everything will be fine.", zh_eg: "放輕鬆，一切都會好的。" },
    { word: "cool down", pos: "片", zh: "冷靜一下", en_eg: "Calm down and cool down a bit.", zh_eg: "冷靜下來，稍微消消氣。" },
    { word: "close", pos: "adj.", zh: "靠近的", en_eg: "Our school is close to the station.", zh_eg: "我們的學校靠近車站。" },
    { word: "monitor", pos: "n.", zh: "監視器", en_eg: "The police checked the security monitor.", zh_eg: "警方檢查了安全監視器。" },
    { word: "sleepwalk", pos: "v.", zh: "夢遊", en_eg: "He sometimes sleepwalks at night.", zh_eg: "他有時晚上會夢遊。" },
    { word: "web", pos: "n.", zh: "網子", en_eg: "A spider is spinning a web.", zh_eg: "蜘蛛正在織網。" },
    { word: "hole", pos: "n.", zh: "洞", en_eg: "There is a hole in my sock.", zh_eg: "我的襪子上有個洞。" },

    // --- Unit 4: What Do You Want to Be in the Future? ---
    { word: "hope", pos: "v./n.", zh: "希望", en_eg: "I hope you can come to my party.", zh_eg: "我希望你能來我的派對。" },
    { word: "future", pos: "n./adj.", zh: "未來 (的)", en_eg: "We should plan well for the future.", zh_eg: "我們應該為未來好好規畫。" },
    { word: "plan", pos: "v./n.", zh: "規劃；計畫", en_eg: "What is your plan for the weekend?", zh_eg: "你週末有什麼計畫？" },
    { word: "lawyer", pos: "n.", zh: "律師", en_eg: "She wants to be a successful lawyer.", zh_eg: "她想成為一名成功的律師。" },
    { word: "job", pos: "n.", zh: "工作", en_eg: "He is looking for a new job.", zh_eg: "他正在找一份新工作。" },
    { word: "get butterflies in one's stomach", pos: "片", zh: "感到緊張", en_eg: "I always get butterflies in my stomach before a speech.", zh_eg: "我在演講前總是感到很緊張。" },
    { word: "worry", pos: "v./n.", zh: "擔心", en_eg: "Don't worry about me; I'll be fine.", zh_eg: "別擔心我，我會很好的。" },
    { word: "keep", pos: "v.", zh: "持續；保持", en_eg: "Keep trying, and you will succeed.", zh_eg: "持續嘗試，你就會成功。" },
    { word: "idea", pos: "n.", zh: "主意；想法", en_eg: "That's a very good idea.", zh_eg: "那真的是個好主意。" },
    { word: "reporter", pos: "n.", zh: "記者", en_eg: "The reporter is interviewing the mayor.", zh_eg: "記者正在採訪市長。" },
    { word: "interview", pos: "v./n.", zh: "採訪；面試", en_eg: "I have a job interview tomorrow morning.", zh_eg: "我明天早上有一個工作面試。" },
    { word: "mail carrier", pos: "n.", zh: "郵差", en_eg: "The mail carrier delivers letters every day.", zh_eg: "郵差每天送信。" },
    { word: "dentist", pos: "n.", zh: "牙醫", en_eg: "You should visit the dentist regularly.", zh_eg: "你應該定期看牙醫。" },
    { word: "factory", pos: "n.", zh: "工廠", en_eg: "My father works in a car factory.", zh_eg: "我父親在汽車工廠工作。" },
    { word: "fisherman", pos: "n.", zh: "漁夫", en_eg: "The fisherman sailed out early in the morning.", zh_eg: "漁夫一大早就航海出海了。" },
    { word: "secretary", pos: "n.", zh: "秘書", en_eg: "She works as a secretary for the boss.", zh_eg: "她為老闆擔任秘書工作。" },
    { word: "boss", pos: "n.", zh: "老闆", en_eg: "Our boss is very kind to everyone.", zh_eg: "我們老闆對大家都很好。" },
    { word: "salesman", pos: "n.", zh: "銷售員；業務員", en_eg: "He is a car salesman.", zh_eg: "他是一名汽車業務員。" },
    { word: "farmer", pos: "n.", zh: "農夫", en_eg: "Farmers work hard in the fields.", zh_eg: "農夫在田裡辛勤工作。" },
    { word: "grow", pos: "v.", zh: "種植；成長", en_eg: "They grow vegetables in their garden.", zh_eg: "他們在花園裡種蔬菜。" },
    { word: "soldier", pos: "n.", zh: "士兵", en_eg: "The brave soldiers protected their country.", zh_eg: "勇敢的士兵保護了他們的國家。" },
    { word: "country", pos: "n.", zh: "國家", en_eg: "Taiwan is a free and democratic country.", zh_eg: "台灣是一個自由民主的國家。" },
    { word: "truck driver", pos: "n.", zh: "卡車司機", en_eg: "Truck drivers work long hours.", zh_eg: "卡車司機工作時數很長。" },
    { word: "drive", pos: "v.", zh: "開 (車)", en_eg: "Can you drive a car?", zh_eg: "你會開車嗎？" },
    { word: "successful", pos: "adj.", zh: "成功的", en_eg: "She is a successful writer.", zh_eg: "她是一位成功的作家。" },
    { word: "find", pos: "v.", zh: "找到；發現", en_eg: "I finally found my lost keys.", zh_eg: "我終於找到我遺失的鑰匙了。" },
    { word: "grade", pos: "n.", zh: "年級；成績", en_eg: "He is in the seventh grade.", zh_eg: "他讀七年級。" },
    { word: "decide", pos: "v.", zh: "決定", en_eg: "Have you decided what to eat?", zh_eg: "你決定好要吃什麼了嗎？" },
    { word: "become", pos: "v.", zh: "成為", en_eg: "She wants to become a doctor.", zh_eg: "她想成為一名醫生。" },
    { word: "relative", pos: "n.", zh: "親戚", en_eg: "Many relatives came to visit us during Chinese New Year.", zh_eg: "農曆新年期間許多親戚來探望我們。" },
    { word: "believe", pos: "v.", zh: "相信", en_eg: "I believe you can make it.", zh_eg: "我相信你辦得到。" },
    { word: "act", pos: "v.", zh: "表演", en_eg: "He likes to act in school plays.", zh_eg: "他喜歡在學校戲劇中表演。" },
    { word: "right", pos: "n.", zh: "權利", en_eg: "Everyone has the right to speak freely.", zh_eg: "每個人都有言論自由的權利。" },
    { word: "put on", pos: "片", zh: "穿上", en_eg: "Put on your coat before going out.", zh_eg: "出門前穿上外套。" },
    { word: "all over", pos: "片", zh: "遍及", en_eg: "People all over the world love peace.", zh_eg: "全世界的人都愛好和平。" },
    { word: "make fun of", pos: "片", zh: "取笑", en_eg: "It is wrong to make fun of others.", zh_eg: "取笑別人是不對的。" },
    { word: "give up", pos: "v.", zh: "放棄", en_eg: "Never give up on your dreams.", zh_eg: "永遠不要放棄你的夢想。" },

    // --- Unit 5: How Do We Go to the Hotel? ---
    { word: "metro", pos: "n.", zh: "捷運", en_eg: "Let's take the metro to the station.", zh_eg: "我們搭捷運去車站吧。" },
    { word: "lost", pos: "adj.", zh: "迷路的", en_eg: "We got lost in the big city.", zh_eg: "我們在大城市裡迷路了。" },
    { word: "map", pos: "n.", zh: "地圖", en_eg: "Look at the city map to find the way.", zh_eg: "看城市地圖來找路。" },
    { word: "ask", pos: "v.", zh: "請求；詢問", en_eg: "If you don't know, ask the teacher.", zh_eg: "如果你不知道，就問老師。" },
    { word: "Excuse me.", pos: "句", zh: "(對不起) 請問…", en_eg: "Excuse me, where is the post office?", zh_eg: "不好意思，請問郵局在哪裡？" },
    { word: "straight", pos: "adj./adv.", zh: "直地；直的", en_eg: "Walk straight, and you'll see it.", zh_eg: "直直走，你就會看到了。" },
    { word: "turn left", pos: "片", zh: "向左轉", en_eg: "Turn left at the next corner.", zh_eg: "在下一個轉角向左轉。" },
    { word: "along", pos: "prep.", zh: "沿著", en_eg: "We walked along the riverbank.", zh_eg: "我們沿著河岸散步。" },
    { word: "block", pos: "n.", zh: "街區", en_eg: "Walk two blocks, and you'll arrive.", zh_eg: "走兩個街區就到了。" },
    { word: "corner", pos: "n.", zh: "轉角；角落", en_eg: "The bookstore is on the corner.", zh_eg: "書店在轉角處。" },
    { word: "across from", pos: "prep.", zh: "在…的對面", en_eg: "The park is across from my house.", zh_eg: "公園在我家對面。" },
    { word: "supermarket", pos: "n.", zh: "超市", en_eg: "I need to buy some milk at the supermarket.", zh_eg: "我需要在超市買些牛奶。" },
    { word: "ground", pos: "n.", zh: "地面", en_eg: "He dropped his pen on the ground.", zh_eg: "他把筆掉在地面上。" },
    { word: "sir", pos: "n.", zh: "先生", en_eg: "Can I help you, sir?", zh_eg: "先生，需要我幫忙嗎？" },
    { word: "on foot", pos: "片", zh: "步行", en_eg: "We went to school on foot today.", zh_eg: "我們今天步行去上學。" },
    { word: "ship", pos: "n.", zh: "輪船", en_eg: "A big ship is sailing on the sea.", zh_eg: "一艘大船正在海上航行。" },
    { word: "taxi", pos: "n.", zh: "計程車", en_eg: "Let's take a taxi because it's late.", zh_eg: "很晚了，我們搭計程車吧。" },
    { word: "bike", pos: "n.", zh: "單車", en_eg: "He rides his bike to school.", zh_eg: "他騎單車上學。" },
    { word: "motorcycle", pos: "n.", zh: "機車", en_eg: "Wear a helmet when riding a motorcycle.", zh_eg: "騎機車時要戴安全帽。" },
    { word: "scooter", pos: "n.", zh: "機車", en_eg: "Scooters are very common in Taiwan.", zh_eg: "機車在台灣非常普遍。" },
    { word: "bank", pos: "n.", zh: "銀行", en_eg: "I need to withdraw money from the bank.", zh_eg: "我需要去銀行領錢。" },
    { word: "fire station", pos: "n.", zh: "消防局", en_eg: "The fire station is near our school.", zh_eg: "消防局就在我們學校附近。" },
    { word: "toy", pos: "n.", zh: "玩具", en_eg: "The boy is playing with his toys.", zh_eg: "小男孩正在玩他的玩具。" },
    { word: "post office", pos: "n.", zh: "郵局", en_eg: "I went to the post office to mail a package.", zh_eg: "我去郵局寄包裹。" },
    { word: "hospital", pos: "n.", zh: "醫院", en_eg: "The doctor works in a big hospital.", zh_eg: "醫生在大醫院工作。" },
    { word: "pool", pos: "n.", zh: "水池", en_eg: "They are swimming in the pool.", zh_eg: "他們正在水池裡游泳。" },
    { word: "go jogging", pos: "片", zh: "慢跑", en_eg: "My father goes jogging every morning.", zh_eg: "我父親每天早上去慢跑。" },
    { word: "go sailing", pos: "片", zh: "玩帆船；航行", en_eg: "They went sailing on the lake.", zh_eg: "他們去湖上玩帆船。" },
    { word: "go surfing", pos: "片", zh: "衝浪", en_eg: "He loves to go surfing in summer.", zh_eg: "他夏天喜歡去衝浪。" },
    { word: "hit", pos: "v.", zh: "碰撞；打擊", en_eg: "The car hit the tree by accident.", zh_eg: "車子意外撞上了樹。" },
    { word: "sound", pos: "n.", zh: "聲音", en_eg: "I heard a strange sound outside.", zh_eg: "我聽到外面有奇怪的聲音。" },
    { word: "bell", pos: "n.", zh: "鐘；鈴", en_eg: "The school bell is ringing.", zh_eg: "學校的鈴聲在響。" },
    { word: "experience", pos: "n./v.", zh: "經歷；經驗", en_eg: "It was an unforgettable experience.", zh_eg: "這是一段難忘的經歷。" },
    { word: "wonderful", pos: "adj.", zh: "美好的", en_eg: "We had a wonderful time together.", zh_eg: "我們度過了一段美好的時光。" },
    { word: "take", pos: "v.", zh: "搭乘；花費", en_eg: "Take the bus to get there.", zh_eg: "搭公車到那裡。" },
    { word: "by", pos: "prep.", zh: "搭乘…方式", en_eg: "She goes to work by MRT.", zh_eg: "她搭捷運上班。" },
    { word: "get off", pos: "片", zh: "下 (車、飛機等)", en_eg: "Get off the bus at the next stop.", zh_eg: "在下一站下車。" },
    { word: "get", pos: "v.", zh: "到達", en_eg: "When will we get home?", zh_eg: "我們什麼時候會到家？" },
    { word: "right", pos: "adj.", zh: "右邊 (的)", en_eg: "Turn right at the corner.", zh_eg: "在轉角右轉。" },
    { word: "fly", pos: "v.", zh: "飛行；駕駛", en_eg: "Birds can fly high in the sky.", zh_eg: "鳥兒可以在天空中高飛。" }
];
console.log("wordDatabase loaded", window.wordDatabase.length);
