// 國中基礎單字庫：字母 A 與 B (共約 160 字)
window.wordDatabase = [
    // --- 字母 A ---
    { word: "able", pos: "adj.", zh: "有能力的", en_eg: "I am able to finish the work on time.", zh_eg: "我有能力準時完成這項工作。" },
    { word: "about", pos: "prep.", zh: "關於", en_eg: "He told me a story about a brave dog.", zh_eg: "他告訴我一個關於勇敢狗狗的故事。" },
    { word: "above", pos: "adv.", zh: "在上方", en_eg: "The bird is flying above the tree.", zh_eg: "鳥兒在樹的上方飛翔。" },
    { word: "abroad", pos: "adv.", zh: "在國外", en_eg: "My sister studies abroad in the USA.", zh_eg: "我姊姊在美國留學。" },
    { word: "absent", pos: "adj.", zh: "缺席的", en_eg: "Tom was absent yesterday because he was sick.", zh_eg: "湯姆昨天因為生病缺席了。" },
    { word: "accept", pos: "v.", zh: "接受", en_eg: "She happily accepted my gift.", zh_eg: "她高興地接受了我的禮物。" },
    { word: "accident", pos: "n.", zh: "意外", en_eg: "He broke his leg in a car accident.", zh_eg: "他在車禍中摔斷了腿。" },
    { word: "achieve", pos: "v.", zh: "達成", en_eg: "You can achieve your dream if you work hard.", zh_eg: "如果你努力，就能達成夢想。" },
    { word: "across", pos: "prep.", zh: "橫過；在對面", en_eg: "The bakery is across the street.", zh_eg: "麵包店在街道對面。" },
    { word: "act", pos: "v.", zh: "行動；表演", en_eg: "He acts like a child sometimes.", zh_eg: "他有時候行為像個小孩。" },
    { word: "action", pos: "n.", zh: "行動", en_eg: "We must take action to protect the earth.", zh_eg: "我們必須採取行動保護地球。" },
    { word: "active", pos: "adj.", zh: "活躍的", en_eg: "My grandmother is very active and healthy.", zh_eg: "我奶奶非常活躍且健康。" },
    { word: "activity", pos: "n.", zh: "活動", en_eg: "Swimming is my favorite summer activity.", zh_eg: "游泳是我最喜歡的夏日活動。" },
    { word: "actor", pos: "n.", zh: "男演員", en_eg: "He is a famous actor in Taiwan.", zh_eg: "他是台灣著名的男演員。" },
    { word: "actress", pos: "n.", zh: "女演員", en_eg: "The actress won an award for her great acting.", zh_eg: "這位女演員因演技精湛獲獎。" },
    { word: "actually", pos: "adv.", zh: "實際上", en_eg: "I look young, but I am actually forty years old.", zh_eg: "我看起來很年輕，但我實際上已經四十歲了。" },
    { word: "add", pos: "v.", zh: "增加", en_eg: "Please add some milk to my black tea.", zh_eg: "請在我的紅茶裡加點牛奶。" },
    { word: "address", pos: "n.", zh: "地址", en_eg: "Write down your name and address here.", zh_eg: "在這裡寫下你的名字和地址。" },
    { word: "admire", pos: "v.", zh: "欽佩", en_eg: "I really admire your courage.", zh_eg: "我非常欽佩你的勇氣。" },
    { word: "adult", pos: "n.", zh: "成人", en_eg: "This movie is only for adults.", zh_eg: "這部電影只適合青少年和成人觀看。" },
    { word: "advice", pos: "n.", zh: "建議", en_eg: "Can you give me some advice on learning English?", zh_eg: "你能給我一些學英文的建議嗎？" },
    { word: "advise", pos: "v.", zh: "勸告", en_eg: "The doctor advised him to stop smoking.", zh_eg: "醫生勸他戒菸。" },
    { word: "affect", pos: "v.", zh: "影響", en_eg: "The bad weather affected our trip.", zh_eg: "壞天氣影響了我們的旅行。" },
    { word: "afraid", pos: "adj.", zh: "害怕的", en_eg: "Don't be afraid of making mistakes.", zh_eg: "不要害怕犯錯。" },
    { word: "after", pos: "prep.", zh: "在...之後", en_eg: "I usually do my homework after dinner.", zh_eg: "我通常在晚餐後做作業。" },
    { word: "afternoon", pos: "n.", zh: "下午", en_eg: "We play basketball every Friday afternoon.", zh_eg: "我們每週五下午打籃球。" },
    { word: "again", pos: "adv.", zh: "再一次", en_eg: "Please say that again. I didn't hear you.", zh_eg: "請再說一次。我沒聽見。" },
    { word: "against", pos: "prep.", zh: "對抗；靠著", en_eg: "He leaned his bike against the wall.", zh_eg: "他把腳踏車靠在牆上。" },
    { word: "age", pos: "n.", zh: "年齡", en_eg: "At the age of ten, she started to play the piano.", zh_eg: "十歲時，她開始彈鋼琴。" },
    { word: "ago", pos: "adv.", zh: "以前", en_eg: "I met him two years ago.", zh_eg: "我兩年前見過他。" },
    { word: "agree", pos: "v.", zh: "同意", en_eg: "I completely agree with your idea.", zh_eg: "我完全同意你的想法。" },
    { word: "ahead", pos: "adv.", zh: "在前方", en_eg: "Go straight ahead and turn left.", zh_eg: "直走然後左轉。" },
    { word: "aim", pos: "n.", zh: "目標", en_eg: "His aim is to become a doctor.", zh_eg: "他的目標是成為一名醫生。" },
    { word: "air", pos: "n.", zh: "空氣", en_eg: "We need fresh air to live.", zh_eg: "我們需要新鮮空氣才能生存。" },
    { word: "airplane", pos: "n.", zh: "飛機", en_eg: "We took an airplane to Japan.", zh_eg: "我們搭飛機去日本。" },
    { word: "airport", pos: "n.", zh: "機場", en_eg: "I will meet you at the airport.", zh_eg: "我會在機場跟你碰面。" },
    { word: "alarm", pos: "n.", zh: "鬧鐘；警報器", en_eg: "I set my alarm for 6 AM.", zh_eg: "我把鬧鐘設定在早上六點。" },
    { word: "alive", pos: "adj.", zh: "活著的", en_eg: "The fish we caught is still alive.", zh_eg: "我們抓到的魚還活著。" },
    { word: "all", pos: "adj.", zh: "全部的", en_eg: "All the students are in the classroom.", zh_eg: "所有學生都在教室裡。" },
    { word: "allow", pos: "v.", zh: "允許", en_eg: "My parents don't allow me to stay out late.", zh_eg: "我父母不允許我晚歸。" },
    { word: "almost", pos: "adv.", zh: "幾乎", en_eg: "I am almost ready to go.", zh_eg: "我幾乎準備好要出發了。" },
    { word: "alone", pos: "adv.", zh: "獨自地", en_eg: "She lives alone in a big house.", zh_eg: "她獨自住在一個大房子裡。" },
    { word: "along", pos: "prep.", zh: "沿著", en_eg: "We walked along the river.", zh_eg: "我們沿著河邊散步。" },
    { word: "aloud", pos: "adv.", zh: "大聲地", en_eg: "Please read the story aloud.", zh_eg: "請大聲朗讀這個故事。" },
    { word: "already", pos: "adv.", zh: "已經", en_eg: "I have already finished my dinner.", zh_eg: "我已經吃完晚餐了。" },
    { word: "also", pos: "adv.", zh: "也", en_eg: "He likes apples, and he also likes bananas.", zh_eg: "他喜歡蘋果，他也喜歡香蕉。" },
    { word: "always", pos: "adv.", zh: "總是", en_eg: "He always gets up early.", zh_eg: "他總是早起。" },
    { word: "ambulance", pos: "n.", zh: "救護車", en_eg: "Call an ambulance right now!", zh_eg: "馬上叫救護車！" },
    { word: "among", pos: "prep.", zh: "在...之中", en_eg: "He is the tallest among his friends.", zh_eg: "在朋友之中他是最高的。" },
    { word: "ancient", pos: "adj.", zh: "古老的", en_eg: "We visited an ancient temple yesterday.", zh_eg: "我們昨天參觀了一座古廟。" },
    { word: "angel", pos: "n.", zh: "天使", en_eg: "The little girl looks like a beautiful angel.", zh_eg: "這小女孩看起來像個美麗的天使。" },
    { word: "anger", pos: "n.", zh: "憤怒", en_eg: "He could not hide his anger.", zh_eg: "他無法隱藏他的憤怒。" },
    { word: "angry", pos: "adj.", zh: "生氣的", en_eg: "My mom was angry because I broke the window.", zh_eg: "我媽很生氣，因為我打破了窗戶。" },
    { word: "ankle", pos: "n.", zh: "腳踝", en_eg: "I twisted my ankle while running.", zh_eg: "我跑步時扭到了腳踝。" },

    // --- 字母 B ---
    { word: "baby", pos: "n.", zh: "嬰兒", en_eg: "The baby is sleeping in the bed.", zh_eg: "嬰兒正在床上睡覺。" },
    { word: "back", pos: "n.", zh: "背部；後面", en_eg: "My back hurts after moving the heavy boxes.", zh_eg: "搬完重箱子後我的背很痛。" },
    { word: "bad", pos: "adj.", zh: "壞的", en_eg: "Smoking is a bad habit.", zh_eg: "抽菸是個壞習慣。" },
    { word: "badminton", pos: "n.", zh: "羽毛球", en_eg: "Let's play badminton this weekend.", zh_eg: "我們這週末來打羽毛球吧。" },
    { word: "bag", pos: "n.", zh: "袋子", en_eg: "I put my books in the school bag.", zh_eg: "我把書放進書包裡。" },
    { word: "bake", pos: "v.", zh: "烘烤", en_eg: "My mother likes to bake cookies.", zh_eg: "我媽媽喜歡烤餅乾。" },
    { word: "bakery", pos: "n.", zh: "麵包店", en_eg: "I bought a cake at the bakery.", zh_eg: "我在麵包店買了一個蛋糕。" },
    { word: "balcony", pos: "n.", zh: "陽台", en_eg: "We stood on the balcony to watch the stars.", zh_eg: "我們站在陽台上看星星。" },
    { word: "ball", pos: "n.", zh: "球", en_eg: "The dog is catching the ball.", zh_eg: "狗正在接球。" },
    { word: "balloon", pos: "n.", zh: "氣球", en_eg: "The child is holding a red balloon.", zh_eg: "小孩拿著一個紅氣球。" },
    { word: "banana", pos: "n.", zh: "香蕉", en_eg: "Monkeys love to eat bananas.", zh_eg: "猴子喜歡吃香蕉。" },
    { word: "band", pos: "n.", zh: "樂團", en_eg: "Mayday is a very popular band.", zh_eg: "五月天是一個非常受歡迎的樂團。" },
    { word: "bank", pos: "n.", zh: "銀行", en_eg: "I need to go to the bank to get some money.", zh_eg: "我必須去銀行領點錢。" },
    { word: "barbecue", pos: "n.", zh: "烤肉", en_eg: "We will have a barbecue on Moon Festival.", zh_eg: "我們中秋節要烤肉。" },
    { word: "barber", pos: "n.", zh: "理髮師", en_eg: "The barber cut my hair very short.", zh_eg: "理髮師把我的頭髮剪得很短。" },
    { word: "bark", pos: "v.", zh: "狗吠", en_eg: "The dog barks at strangers.", zh_eg: "那隻狗對著陌生人吠叫。" },
    { word: "base", pos: "n.", zh: "基礎；底部", en_eg: "The lamp has a heavy metal base.", zh_eg: "這盞燈有一個很重的金屬底座。" },
    { word: "baseball", pos: "n.", zh: "棒球", en_eg: "Many boys in Taiwan love playing baseball.", zh_eg: "台灣很多男孩喜歡打棒球。" },
    { word: "basement", pos: "n.", zh: "地下室", en_eg: "We park our car in the basement.", zh_eg: "我們把車停在地下室。" },
    { word: "basic", pos: "adj.", zh: "基礎的", en_eg: "You need to learn some basic rules first.", zh_eg: "你必須先學一些基礎規則。" },
    { word: "basket", pos: "n.", zh: "籃子", en_eg: "She carries a basket full of apples.", zh_eg: "她提著一個裝滿蘋果的籃子。" },
    { word: "basketball", pos: "n.", zh: "籃球", en_eg: "Jeremy Lin is a great basketball player.", zh_eg: "林書豪是一位偉大的籃球員。" },
    { word: "bat", pos: "n.", zh: "蝙蝠；球棒", en_eg: "A bat usually sleeps during the day.", zh_eg: "蝙蝠通常在白天睡覺。" },
    { word: "bath", pos: "n.", zh: "洗澡", en_eg: "I want to take a hot bath.", zh_eg: "我想要洗個熱水澡。" },
    { word: "bathroom", pos: "n.", zh: "浴室", en_eg: "Wash your hands in the bathroom.", zh_eg: "去浴室洗手。" },
    { word: "be", pos: "v.", zh: "是；存在", en_eg: "I want to be a teacher in the future.", zh_eg: "我未來想成為一名老師。" },
    { word: "beach", pos: "n.", zh: "海灘", en_eg: "We collected shells on the beach.", zh_eg: "我們在海灘上撿貝殼。" },
    { word: "bear", pos: "n.", zh: "熊", en_eg: "The black bear is a strong animal.", zh_eg: "黑熊是很強壯的動物。" },
    { word: "beat", pos: "v.", zh: "擊敗；敲打", en_eg: "Our team beat them in the final game.", zh_eg: "我們隊伍在決賽中擊敗了他們。" },
    { word: "beautiful", pos: "adj.", zh: "美麗的", en_eg: "She is wearing a beautiful dress.", zh_eg: "她穿著一件美麗的洋裝。" },
    { word: "beauty", pos: "n.", zh: "美麗", en_eg: "Taiwan is famous for its natural beauty.", zh_eg: "台灣以其自然之美聞名。" },
    { word: "because", pos: "conj.", zh: "因為", en_eg: "I stayed at home because it was raining.", zh_eg: "我待在家因為下雨了。" },
    { word: "become", pos: "v.", zh: "變成", en_eg: "The weather became cold yesterday.", zh_eg: "昨天天氣變冷了。" },
    { word: "bed", pos: "n.", zh: "床", en_eg: "It's time to go to bed.", zh_eg: "該上床睡覺了。" },
    { word: "bedroom", pos: "n.", zh: "臥室", en_eg: "My bedroom is small but comfortable.", zh_eg: "我的臥室很小但很舒服。" },
    { word: "bee", pos: "n.", zh: "蜜蜂", en_eg: "A bee is flying around the flower.", zh_eg: "一隻蜜蜂在花朵旁飛舞。" },
    { word: "beef", pos: "n.", zh: "牛肉", en_eg: "Beef noodles are very delicious in Taiwan.", zh_eg: "台灣的牛肉麵非常好吃。" },
    { word: "before", pos: "prep.", zh: "在...之前", en_eg: "Wash your hands before dinner.", zh_eg: "晚餐前要洗手。" },
    { word: "begin", pos: "v.", zh: "開始", en_eg: "The movie will begin at 7 PM.", zh_eg: "電影晚上七點開始。" },
    { word: "beginner", pos: "n.", zh: "初學者", en_eg: "This class is suitable for beginners.", zh_eg: "這門課適合初學者。" },
    { word: "beginning", pos: "n.", zh: "開始", en_eg: "At the beginning, it was hard to learn.", zh_eg: "一開始學起來很難。" },
    { word: "behave", pos: "v.", zh: "表現", en_eg: "The boy behaved well in class today.", zh_eg: "這男孩今天在課堂上表現很好。" },
    { word: "behind", pos: "prep.", zh: "在...後面", en_eg: "The cat is hiding behind the sofa.", zh_eg: "貓躲在沙發後面。" },
    { word: "believe", pos: "v.", zh: "相信", en_eg: "I believe you can do it.", zh_eg: "我相信你做得到。" },
    { word: "bell", pos: "n.", zh: "鐘；鈴鐺", en_eg: "The school bell is ringing.", zh_eg: "學校的鐘聲在響。" },
    { word: "belong", pos: "v.", zh: "屬於", en_eg: "This book belongs to my brother.", zh_eg: "這本書屬於我弟弟。" },
    { word: "below", pos: "prep.", zh: "在...下方", en_eg: "Please read the text below the picture.", zh_eg: "請閱讀圖片下方的文字。" },
    { word: "belt", pos: "n.", zh: "皮帶", en_eg: "He is wearing a black leather belt.", zh_eg: "他繫著一條黑色的皮帶。" },
    { word: "bench", pos: "n.", zh: "長椅", en_eg: "We sat on a bench in the park.", zh_eg: "我們坐在公園的長椅上。" },
    { word: "beside", pos: "prep.", zh: "在...旁邊", en_eg: "Come and sit beside me.", zh_eg: "過來坐在我旁邊。" },
    { word: "between", pos: "prep.", zh: "在...之間", en_eg: "The library is between the bank and the post office.", zh_eg: "圖書館在銀行和郵局之間。" },
    { word: "beyond", pos: "prep.", zh: "越過；超過", en_eg: "The beautiful lake is beyond those mountains.", zh_eg: "那座美麗的湖在群山之外。" },
    { word: "bicycle", pos: "n.", zh: "腳踏車", en_eg: "He rides his bicycle to school every day.", zh_eg: "他每天騎腳踏車上學。" },
    { word: "big", pos: "adj.", zh: "大的", en_eg: "They live in a very big house.", zh_eg: "他們住在一間很大的房子裡。" },
    { word: "bike", pos: "n.", zh: "腳踏車", en_eg: "I bought a new bike yesterday.", zh_eg: "我昨天買了一輛新腳踏車。" },
    { word: "bite", pos: "v.", zh: "咬", en_eg: "Does your dog bite?", zh_eg: "你的狗會咬人嗎？" },
    { word: "bitter", pos: "adj.", zh: "苦的", en_eg: "This coffee tastes too bitter.", zh_eg: "這杯咖啡喝起來太苦了。" },
    { word: "black", pos: "adj.", zh: "黑色的", en_eg: "She has long black hair.", zh_eg: "她有一頭黑色長髮。" },
    { word: "blackboard", pos: "n.", zh: "黑板", en_eg: "The teacher wrote on the blackboard.", zh_eg: "老師在黑板上寫字。" },
    { word: "blame", pos: "v.", zh: "責怪", en_eg: "Don't blame yourself for the mistake.", zh_eg: "不要為這個錯誤責怪你自己。" },
    { word: "blank", pos: "adj.", zh: "空白的", en_eg: "Please fill in the blank with the correct word.", zh_eg: "請用正確的字填入空白處。" },
    { word: "blanket", pos: "n.", zh: "毯子", en_eg: "It's cold. I need a blanket.", zh_eg: "好冷。我需要一條毯子。" },
    { word: "blind", pos: "adj.", zh: "盲的", en_eg: "He helped the blind man cross the street.", zh_eg: "他幫那位盲人過馬路。" },
    { word: "block", pos: "n.", zh: "街區；積木", en_eg: "The supermarket is three blocks away.", zh_eg: "超市在三個街區外。" },
    { word: "blood", pos: "n.", zh: "血", en_eg: "He lost a lot of blood in the accident.", zh_eg: "他在意外中流了很多血。" },
    { word: "blow", pos: "v.", zh: "吹", en_eg: "The wind is blowing hard today.", zh_eg: "今天的風吹得很大。" },
    { word: "blue", pos: "adj.", zh: "藍色的", en_eg: "The sky is so blue today.", zh_eg: "今天的天空真藍。" },
    { word: "boat", pos: "n.", zh: "小船", en_eg: "We rented a boat on the lake.", zh_eg: "我們在湖上租了一艘小船。" },
    { word: "body", pos: "n.", zh: "身體", en_eg: "Exercise is good for your body and mind.", zh_eg: "運動對你的身心都有益。" },
    { word: "boil", pos: "v.", zh: "沸騰；煮", en_eg: "Please boil some water for the tea.", zh_eg: "請燒點水泡茶。" },
    { word: "bomb", pos: "n.", zh: "炸彈", en_eg: "The police found a bomb in the building.", zh_eg: "警察在大樓裡發現了一枚炸彈。" },
    { word: "bone", pos: "n.", zh: "骨頭", en_eg: "The dog is chewing a bone.", zh_eg: "狗正在啃骨頭。" },
    { word: "book", pos: "n.", zh: "書本", en_eg: "I enjoy reading books in my free time.", zh_eg: "我喜歡在空閒時看書。" },
    { word: "bookcase", pos: "n.", zh: "書櫃", en_eg: "Put the books back in the bookcase.", zh_eg: "把書放回書櫃裡。" },
    { word: "bookstore", pos: "n.", zh: "書店", en_eg: "I bought a dictionary at the bookstore.", zh_eg: "我在書店買了一本字典。" },
    { word: "boring", pos: "adj.", zh: "無聊的", en_eg: "The movie was so boring that I fell asleep.", zh_eg: "這部電影太無聊了，我都睡著了。" },
    { word: "born", pos: "v.", zh: "出生", en_eg: "I was born in Taiwan.", zh_eg: "我出生在台灣。" },
    { word: "borrow", pos: "v.", zh: "借入", en_eg: "Can I borrow your pen for a minute?", zh_eg: "我可以借你的筆用一下嗎？" },
    { word: "boss", pos: "n.", zh: "老闆", en_eg: "My boss is a very nice person.", zh_eg: "我的老闆是個很好的人。" },
    { word: "both", pos: "adj.", zh: "兩者", en_eg: "Both of my parents are teachers.", zh_eg: "我的父母都是老師。" },
    { word: "bother", pos: "v.", zh: "打擾", en_eg: "Please don't bother me while I'm studying.", zh_eg: "我讀書時請不要打擾我。" },
    { word: "bottle", pos: "n.", zh: "瓶子", en_eg: "I need a bottle of water.", zh_eg: "我需要一瓶水。" },
    { word: "bottom", pos: "n.", zh: "底部", en_eg: "Read the notes at the bottom of the page.", zh_eg: "請閱讀頁面底部的註解。" },
    { word: "bow", pos: "v.", zh: "鞠躬", en_eg: "The students bow to the teacher.", zh_eg: "學生向老師鞠躬。" },
    { word: "bowl", pos: "n.", zh: "碗", en_eg: "I ate a bowl of rice for dinner.", zh_eg: "我晚餐吃了一碗飯。" },
    { word: "box", pos: "n.", zh: "箱子", en_eg: "There is a gift in the box.", zh_eg: "箱子裡有一個禮物。" },
    { word: "boy", pos: "n.", zh: "男孩", en_eg: "The little boy is playing in the park.", zh_eg: "小男孩正在公園裡玩耍。" },
    { word: "brain", pos: "n.", zh: "大腦", en_eg: "The human brain is very complex.", zh_eg: "人類的大腦非常複雜。" },
    { word: "branch", pos: "n.", zh: "樹枝；分公司", en_eg: "The bird is standing on a branch.", zh_eg: "鳥停在樹枝上。" },
    { word: "brave", pos: "adj.", zh: "勇敢的", en_eg: "The brave fireman saved the child.", zh_eg: "勇敢的消防員救了那個小孩。" },
    { word: "bread", pos: "n.", zh: "麵包", en_eg: "I usually have some bread for breakfast.", zh_eg: "我早餐通常吃些麵包。" },
    { word: "break", pos: "v.", zh: "打破；弄壞", en_eg: "Be careful not to break the glass.", zh_eg: "小心別打破玻璃杯。" },
    { word: "breakfast", pos: "n.", zh: "早餐", en_eg: "What did you have for breakfast today?", zh_eg: "你今天早餐吃什麼？" },
    { word: "bridge", pos: "n.", zh: "橋", en_eg: "We walked across the bridge.", zh_eg: "我們走過那座橋。" },
    { word: "bright", pos: "adj.", zh: "明亮的", en_eg: "The sun is very bright today.", zh_eg: "今天的陽光很明亮。" },
    { word: "bring", pos: "v.", zh: "帶來", en_eg: "Don't forget to bring your umbrella.", zh_eg: "別忘了帶你的傘。" },
    { word: "brother", pos: "n.", zh: "兄弟", en_eg: "I have one older brother.", zh_eg: "我有一個哥哥。" },
    { word: "brown", pos: "adj.", zh: "棕色的", en_eg: "He has big brown eyes.", zh_eg: "他有一雙棕色的大眼睛。" },
    { word: "brush", pos: "v.", zh: "刷", en_eg: "Remember to brush your teeth before bed.", zh_eg: "睡前記住要刷牙。" },
    { word: "bug", pos: "n.", zh: "蟲子", en_eg: "There is a bug on the wall.", zh_eg: "牆上有一隻蟲子。" },
    { word: "build", pos: "v.", zh: "建造", en_eg: "They plan to build a new hospital here.", zh_eg: "他們計畫在這裡建一家新醫院。" },
    { word: "building", pos: "n.", zh: "建築物", en_eg: "Taipei 101 is a very tall building.", zh_eg: "台北101是一棟很高的建築物。" },
    { word: "bun", pos: "n.", zh: "小圓麵包；包子", en_eg: "I ate a pork bun for a snack.", zh_eg: "我吃了一個豬肉包當點心。" },
    { word: "burn", pos: "v.", zh: "燃燒；燒傷", en_eg: "Be careful not to burn yourself.", zh_eg: "小心別燙傷你自己。" },
    { word: "bus", pos: "n.", zh: "公車", en_eg: "I take the bus to work every day.", zh_eg: "我每天搭公車上班。" },
    { word: "business", pos: "n.", zh: "生意；商業", en_eg: "His business is growing fast.", zh_eg: "他的生意成長得很快。" },
    { word: "busy", pos: "adj.", zh: "忙碌的", en_eg: "I am too busy to go to the movies.", zh_eg: "我太忙了，沒辦法去看電影。" },
    { word: "but", pos: "conj.", zh: "但是", en_eg: "I like dogs, but I don't like cats.", zh_eg: "我喜歡狗，但不喜歡貓。" },
    { word: "butter", pos: "n.", zh: "奶油", en_eg: "I like to put butter on my toast.", zh_eg: "我喜歡在吐司上塗奶油。" },
    { word: "butterfly", pos: "n.", zh: "蝴蝶", en_eg: "A beautiful butterfly flew into the room.", zh_eg: "一隻美麗的蝴蝶飛進了房間。" },
    { word: "button", pos: "n.", zh: "按鈕；鈕扣", en_eg: "Push the red button to start the machine.", zh_eg: "按下紅色按鈕啟動機器。" },
    { word: "buy", pos: "v.", zh: "買", en_eg: "I need to buy some eggs from the supermarket.", zh_eg: "我需要去超市買些雞蛋。" },
    { word: "by", pos: "prep.", zh: "藉由；在...旁邊", en_eg: "She goes to school by bus.", zh_eg: "她搭公車上學。" }
];


